weights: /home/class3/hsl_prj/yolov5/runs/train/final_train/weights/last.pt
cfg: ''
data: datasets/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 120
batch_size: 64
imgsz: 320
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: final_train
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
save_dir: runs/train/final_train3
